apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitgram-deployment
  labels:
    app: fitgram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitgram
  template:
    metadata:
      labels:
        app: fitgram
    spec:
      containers:
        - name: fitgram
          image: jamesmjkim/fitgram-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: RDS_USERNAME
              value: jamesk
            - name: RDS_HOSTNAME
              value: pg-service
            - name: RDS_DBNAME
              value: postgresdb
            - name: RDS_PASSWORD
              value: admin
            - name: RDS_PORT
              value: '5555'
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: fg-service
  labels:
    app: fitgram
spec:
  type: LoadBalancer
  selector:
    app: fitgram
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30010
