apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fitgram-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fitgram
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
