apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgres
          image: jamesmjkim/fitgram-database:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: jamesk
            - name: POSTGRES_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  labels:
    db: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5432
  selector:
    db: postgres
